"""
============================================
FILE 3 OF 8: EMBEDDING_GENERATOR.PY — Creating Vector Embeddings
============================================

📝 PURPOSE:
    This is where the MAGIC happens. We convert human-readable text
    into numbers that computers can understand and compare.
    
    After chunking (chunker.py), we have pieces of text like:
    "Machine learning is a subset of artificial intelligence..."
    
    But computers can't understand text! They only understand numbers.
    
    Embeddings convert text → list of numbers (a "vector"):
    "Machine learning is..." → [0.12, -0.34, 0.56, 0.78, -0.01, ...]
    
    The BRILLIANT thing is: similar texts produce similar vectors!
    "Machine learning" → [0.12, -0.34, 0.56, ...]  
    "AI and ML models" → [0.13, -0.33, 0.55, ...]  ← CLOSE! (similar meaning)
    "Italian cooking"  → [-0.8,  0.92, -0.1, ...]  ← FAR! (different meaning)

🎓 CONCEPTS COVERED:
    1. Embeddings — What they are and why they matter
    2. Vector Space — The mathematical space where text lives as vectors
    3. Dimensionality — What 384 or 1536 dimensions mean
    4. Cosine Similarity — How to measure vector closeness
    5. Embedding Models — Local (free) vs API (paid) options
    6. Tokenization — How models break text into tokens before embedding
    7. Semantic Similarity — Finding text with similar MEANING, not just matching words

🔗 HOW IT CONNECTS:
    data_loader.py  →  chunker.py  →  embedding_generator.py  →  vector_db.py
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
                                      YOU ARE HERE
    
    Input: List[Document] (chunks from chunker.py)
    Output: List of vectors (numbers) + stored in vector_db.py

💡 DEEP DIVE — WHY EMBEDDINGS WORK:
    
    Traditional search (keyword matching):
    Query: "How do cars work?"
    ❌ Won't find: "The mechanics of automobiles" (no matching words!)
    
    Semantic search (embedding similarity):
    Query: "How do cars work?"  → vector: [0.4, 0.8, -0.2, ...]
    Doc:   "The mechanics of automobiles" → vector: [0.39, 0.81, -0.19, ...]
    ✅ Found! Vectors are almost identical because MEANING is similar.
    
    This is why RAG uses embeddings instead of keyword search.
    Embeddings understand MEANING, not just words.

💡 INTERVIEW QUESTION: "Explain how text embeddings work."
    ANSWER:
    "Text embeddings are dense vector representations of text in a continuous
    vector space. They're generated by neural networks (like BERT or 
    sentence-transformers) that have been trained on massive text corpora 
    to understand language semantics. The training objective is typically 
    contrastive — similar texts should have similar vectors and dissimilar 
    texts should have distant vectors. The resulting vectors capture semantic 
    meaning, enabling operations like similarity search, clustering, and 
    classification in the vector space."

============================================
"""

import numpy as np
from typing import List, Optional, Union
from data_loader import Document
from config import config


# ============================================
# WHAT IS TOKENIZATION?
# ============================================
# Before creating embeddings, models need to TOKENIZE text.
# Tokenization = splitting text into smaller units (tokens).
#
# 📊 EXAMPLES:
#
# Word-level tokenization:
#   "I love machine learning" → ["I", "love", "machine", "learning"]
#
# Subword tokenization (BPE — Byte Pair Encoding):
#   "unhappiness" → ["un", "happi", "ness"]
#   "tokenization" → ["token", "ization"]
#
# WHY SUBWORD? 
# Language has too many words! What if the model sees a word 
# it's never seen before? With subword tokenization:
# - "unhappiness" = "un" + "happi" + "ness" — all known subwords!
# - Even brand new words can be broken into known pieces
#
# 💡 TOKEN ≠ WORD
# "Hello world!" → 3 tokens in some models, 2 in others.
# Rule of thumb: 1 token ≈ 4 characters in English
# "Machine learning" = 3 tokens (Mach, ine, learning)
#
# 💡 WHY TOKENS MATTER FOR YOU:
# - LLMs have TOKEN limits (not character limits)
# - Embedding models have TOKEN limits too
# - You pay per token when using APIs
# - "all-MiniLM-L6-v2" handles up to 512 tokens per input
# ============================================


class EmbeddingGenerator:
    """
    Generates vector embeddings from text.
    
    Supports two modes:
    1. LOCAL mode (FREE): Uses sentence-transformers library
       - Model: all-MiniLM-L6-v2 (384 dimensions)
       - Runs on YOUR computer
       - No API key needed
       - Good quality for learning/prototyping
       
    2. OPENAI mode (PAID): Uses OpenAI's embedding API
       - Model: text-embedding-3-small (1536 dimensions)
       - Runs on OpenAI's servers
       - Requires API key + costs $$$
       - Higher quality for production
    
    🎓 DEEP EXPLANATION — Dimensions:
    
    A 384-dimensional embedding is a list of 384 numbers:
    [0.12, -0.34, 0.56, 0.78, -0.01, ..., 0.43]  ← 384 numbers total
    
    Each dimension captures some ASPECT of meaning:
    - Dimension 1 might relate to "formality" (formal vs casual)
    - Dimension 2 might relate to "topic" (science vs art)
    - Dimension 47 might relate to "sentiment" (positive vs negative)
    
    (We don't know exactly what each dimension means — the model 
    learned these representations during training)
    
    More dimensions = more nuanced understanding:
    - 384 dims: Good for general use (our local model)
    - 1536 dims: Very detailed (OpenAI's model)
    - 3072 dims: Extremely detailed (OpenAI's large model)
    
    But more dimensions also means:
    - More storage space
    - Slower similarity search
    - Higher cost
    
    💡 INTERVIEW INSIGHT:
    "384 dimensions" might sound arbitrary, but it's a tradeoff:
    - Research shows quality plateaus around 768-1024 dimensions
    - 384 is an efficient compromise (half the standard 768)
    - The model was trained to compress meaning into these dimensions
    """
    
    def __init__(self, model_type: str = None):
        """
        Initialize the embedding generator.
        
        Args:
            model_type: "local" or "openai" (defaults to config setting)
        """
        self.model_type = model_type or config.embedding.model_type
        self.model = None
        self.dimension = None
        
        # Load the appropriate model
        if self.model_type == "local":
            self._load_local_model()
        elif self.model_type == "openai":
            self._setup_openai()
        else:
            raise ValueError(
                f"❌ Unknown model type: '{self.model_type}'\n"
                f"   Use 'local' (free, runs on your machine) or 'openai' (paid, API)"
            )
    
    def _load_local_model(self):
        """
        Load a local sentence-transformer model.
        
        🎓 WHAT IS SENTENCE-TRANSFORMERS?
        
        It's a Python library that provides pre-trained models specifically
        designed to create good sentence/paragraph embeddings.
        
        The model 'all-MiniLM-L6-v2':
        - 'all': Trained on diverse data (not domain-specific)
        - 'MiniLM': Microsoft's efficient mini language model architecture
        - 'L6': 6 transformer layers (small but effective)
        - 'v2': Second version (improved training)
        
        Size: ~80MB (downloads once, then cached locally)
        Speed: Very fast, even on CPU
        Quality: Good for prototyping, decent for production
        
        💡 INTERVIEW: "Why all-MiniLM-L6-v2?"
        Because it's the best balance of quality, speed, and size.
        For production, consider:
        - multilingual-e5-large (for multiple languages)
        - bge-large-en-v1.5 (MTEB benchmark leader)
        - text-embedding-3-small (if using OpenAI API)
        """
        try:
            from sentence_transformers import SentenceTransformer
        except ImportError:
            raise ImportError(
                "sentence-transformers is not installed!\n"
                "Run: pip install sentence-transformers\n\n"
                "This library provides pre-trained embedding models that\n"
                "run locally on your computer — no API key needed!"
            )
        
        model_name = config.embedding.local_model_name
        print(f"🧮 Loading local embedding model: {model_name}")
        print(f"   (First run will download ~80MB model, then it's cached)")
        
        self.model = SentenceTransformer(model_name)
        self.dimension = self.model.get_sentence_embedding_dimension()
        
        print(f"   ✅ Model loaded! Embedding dimension: {self.dimension}")
    
    def _setup_openai(self):
        """
        Set up OpenAI embedding client.
        
        🎓 HOW OPENAI EMBEDDINGS WORK:
        
        1. You send text to OpenAI's API
        2. Their servers run the text through their model
        3. You get back a vector of 1536/3072 numbers
        
        Pricing (as of 2024):
        - text-embedding-3-small: $0.02 per 1M tokens
        - text-embedding-3-large: $0.13 per 1M tokens
        
        For 1000 document chunks (avg 200 tokens each):
        200,000 tokens × $0.02/1M = $0.004 (less than 1 cent!)
        
        Very affordable, but for learning, local is fine.
        """
        try:
            from openai import OpenAI
        except ImportError:
            raise ImportError(
                "openai library is not installed!\n"
                "Run: pip install openai"
            )
        
        if not config.openai_api_key:
            raise ValueError(
                "❌ OpenAI API key not found!\n"
                "   Set OPENAI_API_KEY in your .env file\n"
                "   Or switch to local embeddings: EMBEDDING_MODEL=local"
            )
        
        self.model = OpenAI(api_key=config.openai_api_key)
        self.dimension = 1536  # text-embedding-3-small dimension
        
        print(f"🌐 Using OpenAI embeddings: {config.embedding.openai_model_name}")
        print(f"   Dimension: {self.dimension}")
    
    def embed_text(self, text: str) -> List[float]:
        """
        Convert a single text string into a vector embedding.
        
        This is the CORE function — it transforms text into numbers.
        
        Args:
            text: Any string of text
            
        Returns:
            List[float]: A vector of numbers representing the text's meaning
            
        Example:
            >>> gen = EmbeddingGenerator(model_type="local")
            >>> vector = gen.embed_text("Machine learning is fascinating")
            >>> print(f"Vector has {len(vector)} dimensions")
            >>> print(f"First 5 values: {vector[:5]}")
            # Output: Vector has 384 dimensions
            # Output: First 5 values: [0.12, -0.34, 0.56, 0.78, -0.01]
        """
        if not text or not text.strip():
            raise ValueError("❌ Cannot embed empty text!")
        
        if self.model_type == "local":
            # ============================================
            # LOCAL EMBEDDING
            # The model.encode() method:
            # 1. Tokenizes the text (splits into subword tokens)
            # 2. Passes tokens through the neural network
            # 3. Returns the pooled output as a vector
            #
            # convert_to_numpy=True: Returns numpy array (faster math)
            # normalize_embeddings=True: Scales vector to length 1
            #   WHY NORMALIZE?
            #   Normalized vectors make cosine similarity = dot product
            #   This speeds up similarity search significantly.
            # ============================================
            embedding = self.model.encode(
                text, 
                convert_to_numpy=True,
                normalize_embeddings=True
            )
            return embedding.tolist()
        
        elif self.model_type == "openai":
            # ============================================
            # OPENAI API EMBEDDING
            # Send text to OpenAI's servers, get vector back
            # ============================================
            response = self.model.embeddings.create(
                input=text,
                model=config.embedding.openai_model_name
            )
            return response.data[0].embedding
    
    def embed_texts(self, texts: List[str]) -> List[List[float]]:
        """
        Convert multiple texts into embeddings.
        
        More efficient than calling embed_text() one by one because:
        - Local model: Batches all texts through GPU/CPU at once
        - OpenAI API: Sends all texts in one API call (fewer HTTP requests)
        
        Args:
            texts: List of text strings
            
        Returns:
            List of embedding vectors (one per text)
            
        Example:
            >>> texts = ["Hello world", "Machine learning", "Italian cooking"]
            >>> vectors = gen.embed_texts(texts)
            >>> print(f"Generated {len(vectors)} vectors")
        """
        if not texts:
            return []
        
        print(f"🧮 Generating embeddings for {len(texts)} texts...")
        
        if self.model_type == "local":
            embeddings = self.model.encode(
                texts,
                convert_to_numpy=True,
                normalize_embeddings=True,
                show_progress_bar=True,  # Shows a progress bar!
                batch_size=32  # Process 32 texts at a time
            )
            result = embeddings.tolist()
        
        elif self.model_type == "openai":
            # ============================================
            # BATCH EMBEDDING WITH OPENAI
            # OpenAI accepts up to 2048 texts per request
            # We batch to stay within limits
            # ============================================
            result = []
            batch_size = 100  # API batch size
            
            for i in range(0, len(texts), batch_size):
                batch = texts[i:i + batch_size]
                response = self.model.embeddings.create(
                    input=batch,
                    model=config.embedding.openai_model_name
                )
                batch_embeddings = [item.embedding for item in response.data]
                result.extend(batch_embeddings)
        
        print(f"   ✅ Generated {len(result)} embeddings (dim={self.dimension})")
        return result
    
    def embed_documents(self, documents: List[Document]) -> tuple:
        """
        Embed all documents and return texts, embeddings, and metadata.
        
        This is the convenience method that handles Document objects.
        It extracts text, generates embeddings, and prepares metadata
        for storage in the vector database.
        
        Args:
            documents: List of Document objects (chunks from chunker.py)
            
        Returns:
            Tuple of (texts, embeddings, metadatas, ids):
                - texts: List of original text strings
                - embeddings: List of embedding vectors
                - metadatas: List of metadata dicts
                - ids: List of unique IDs for each chunk
                
        💡 WHY RETURN ALL FOUR?
        Because ChromaDB (our vector database) needs all of these:
        - ids: Unique identifier for each stored item
        - embeddings: The vectors for similarity search
        - documents: Original text (for returning to the user)
        - metadatas: Extra info (source file, page number, etc.)
        """
        texts = [doc.text for doc in documents]
        metadatas = [doc.metadata for doc in documents]
        
        # Generate unique IDs for each chunk
        ids = []
        for i, doc in enumerate(documents):
            source = doc.metadata.get("source", "unknown")
            chunk_idx = doc.metadata.get("chunk_index", i)
            doc_idx = doc.metadata.get("original_doc_index", 0)
            # Create a readable ID like "report_pdf_doc0_chunk3"
            clean_source = source.replace(".", "_").replace(" ", "_")
            doc_id = f"{clean_source}_doc{doc_idx}_chunk{chunk_idx}"
            ids.append(doc_id)
        
        # Generate embeddings
        embeddings = self.embed_texts(texts)
        
        return texts, embeddings, metadatas, ids


# ============================================
# SIMILARITY FUNCTIONS
# ============================================
# These are the mathematical operations that make 
# semantic search possible.
#
# 💡 INTERVIEW DEEP DIVE — Similarity Metrics:
#
# 1. COSINE SIMILARITY (Most Common in NLP)
#    Measures the angle between two vectors.
#    Range: -1 (opposite) to 1 (identical)
#    Ignores magnitude, cares only about direction.
#    
#    Formula: cos(θ) = (A · B) / (|A| × |B|)
#    
#    Why for text: Because we care about the DIRECTION of meaning,
#    not the length. A long text about ML and a short text about ML
#    should be similar, even though one has more words.
#
# 2. EUCLIDEAN DISTANCE  
#    Measures straight-line distance between two points.
#    Range: 0 (identical) to ∞ (very different)
#    
#    Formula: d = √(Σ(ai - bi)²)
#    
#    Less common for text because it's affected by vector magnitude.
#
# 3. DOT PRODUCT
#    Simple multiplication and sum.
#    Range: -∞ to ∞
#    
#    Formula: A · B = Σ(ai × bi)
#    
#    Fast to compute. If vectors are normalized (length = 1),
#    dot product = cosine similarity!
# ============================================

def cosine_similarity(vec_a: List[float], vec_b: List[float]) -> float:
    """
    Calculate cosine similarity between two vectors.
    
    This measures how similar two texts are based on their embeddings.
    
    Args:
        vec_a: First embedding vector
        vec_b: Second embedding vector
        
    Returns:
        float: Similarity score from -1 (opposite) to 1 (identical)
        
    Example:
        >>> gen = EmbeddingGenerator("local")
        >>> v1 = gen.embed_text("Machine learning is great")
        >>> v2 = gen.embed_text("AI and ML are amazing")
        >>> v3 = gen.embed_text("I love Italian food")
        >>> print(f"ML vs AI: {cosine_similarity(v1, v2):.4f}")   # ~0.8
        >>> print(f"ML vs Food: {cosine_similarity(v1, v3):.4f}")  # ~0.1
    """
    a = np.array(vec_a)
    b = np.array(vec_b)
    
    # Dot product of A and B
    dot_product = np.dot(a, b)
    
    # Magnitudes (lengths) of A and B
    magnitude_a = np.linalg.norm(a)
    magnitude_b = np.linalg.norm(b)
    
    # Avoid division by zero
    if magnitude_a == 0 or magnitude_b == 0:
        return 0.0
    
    return float(dot_product / (magnitude_a * magnitude_b))


# ============================================
# TEST & DEMO SECTION
# ============================================

if __name__ == "__main__":
    from rich import print as rprint
    from rich.panel import Panel
    from rich.table import Table
    
    rprint(Panel.fit(
        "[bold cyan]🧮 EMBEDDING GENERATOR — Test & Demo[/bold cyan]\n\n"
        "This module converts text into numerical vectors.\n"
        "Similar texts produce similar vectors — that's the magic!",
        title="File 3 of 8",
        border_style="cyan"
    ))
    
    # Initialize the embedding generator (using free local model)
    rprint("\n[yellow]Initializing local embedding model...[/yellow]")
    gen = EmbeddingGenerator(model_type="local")
    
    # ============================================
    # DEMO 1: Basic embedding
    # ============================================
    rprint(f"\n[bold green]--- Demo 1: Create an embedding ---[/bold green]")
    text = "Machine learning is a subset of artificial intelligence"
    vector = gen.embed_text(text)
    
    rprint(f"Text: '{text}'")
    rprint(f"Vector dimensions: {len(vector)}")
    rprint(f"First 10 values: {[round(v, 4) for v in vector[:10]]}")
    rprint(f"Vector magnitude: {np.linalg.norm(vector):.4f} (should be ~1.0 if normalized)")
    
    # ============================================
    # DEMO 2: Semantic similarity
    # ============================================
    rprint(f"\n[bold green]--- Demo 2: Semantic Similarity ---[/bold green]")
    rprint("[dim]Watch how similar concepts have similar vectors![/dim]\n")
    
    test_pairs = [
        ("Machine learning is powerful", "AI and deep learning are amazing"),
        ("Machine learning is powerful", "The weather is sunny today"),
        ("How do cars work?", "The mechanics of automobiles"),
        ("Python programming language", "Coding in Python"),
        ("I love pizza", "Italian cuisine is delicious"),
        ("I love pizza", "Quantum physics equations"),
    ]
    
    table = Table(title="🎯 Semantic Similarity Scores")
    table.add_column("Text A", style="cyan", width=35)
    table.add_column("Text B", style="green", width=35)
    table.add_column("Similarity", style="yellow", justify="right")
    table.add_column("Verdict", style="bold")
    
    for text_a, text_b in test_pairs:
        vec_a = gen.embed_text(text_a)
        vec_b = gen.embed_text(text_b)
        similarity = cosine_similarity(vec_a, vec_b)
        
        # Color code the verdict
        if similarity > 0.7:
            verdict = "🟢 Very Similar"
        elif similarity > 0.4:
            verdict = "🟡 Somewhat Similar"
        else:
            verdict = "🔴 Different"
        
        table.add_row(text_a, text_b, f"{similarity:.4f}", verdict)
    
    rprint(table)
    
    # ============================================
    # DEMO 3: Batch embedding from Documents
    # ============================================
    rprint(f"\n[bold green]--- Demo 3: Batch Document Embedding ---[/bold green]")
    
    docs = [
        Document(text="RAG combines retrieval with generation", metadata={"source": "rag.txt", "chunk_index": 0}),
        Document(text="Vector databases store embeddings for search", metadata={"source": "rag.txt", "chunk_index": 1}),
        Document(text="LLMs generate text based on prompts", metadata={"source": "rag.txt", "chunk_index": 2}),
    ]
    
    texts, embeddings, metadatas, ids = gen.embed_documents(docs)
    
    rprint(f"\nEmbedded {len(embeddings)} documents:")
    for i, (text, emb, meta, doc_id) in enumerate(zip(texts, embeddings, metadatas, ids)):
        rprint(f"  [{i}] ID: {doc_id}")
        rprint(f"      Text: '{text}'")
        rprint(f"      Vector: [{emb[0]:.4f}, {emb[1]:.4f}, ... ] ({len(emb)} dims)")
    
    rprint(Panel.fit(
        "[bold green]✅ Embedding Generator working correctly![/bold green]\n\n"
        "[yellow]WHAT YOU LEARNED:[/yellow]\n"
        "• Embeddings = text converted to numerical vectors\n"
        "• Similar meaning → similar vectors\n"
        "• Cosine similarity measures vector closeness (-1 to 1)\n"
        "• Local models are FREE (sentence-transformers)\n"
        "• Tokenization happens INSIDE the model before embedding\n"
        "• Normalization makes similarity computation faster\n\n"
        "[yellow]INTERVIEW GOLD:[/yellow]\n"
        "• 'What are embeddings?' → Dense vector representations that\n"
        "  capture semantic meaning in continuous vector space.\n"
        "• 'Cosine vs Euclidean?' → Cosine is direction-based (better\n"
        "  for text), Euclidean is distance-based.\n"
        "• 'Why normalize?' → Makes dot product = cosine similarity.\n\n"
        "[yellow]NEXT STEP:[/yellow] vector_db.py — storing and searching vectors",
        title="Summary",
        border_style="green"
    ))
